<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.

# We define this to allow the configuration file to be explicitly 
# located in /etc/mediawiki.
# Change this if you are setting up multisite wikis on your server.
define('MW_INSTALL_PATH','/srv/www/it-governance.freecode.no_80/htdocs/mediawiki/');

if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

# If PHP's memory limit is very low, some operations may fail.
ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wbReadOnly = "Upgrading to MediaWiki 1.16.2";
$wgSitename         = "IT frameworks";
# old logo
#$wgLogo	= "https://it-governance.freecode.no/w/images/2/2f/Freecode_wiki_logo.png";
$wgLogo	= "http://it-governance.freecode.no/w/images/f/f5/Anthill_logo.png";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
$wgScriptPath       = "/w";
$wgScript           = "$wgScriptPath/index.php";
$wgArticlePath      = "/wiki/$1";
$wgScriptExtension  = ".php";

## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL

$wgEnableEmail      = true;
$wgEnableUserEmail  = true;

$wgEmergencyContact = "webmaster@freecode.no";
$wgPasswordSender = "webmaster@freecode.no";

$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['user']['edit'] = true;

## For a detailed description of the following switches see
## http://www.mediawiki.org/wiki/Extension:Email_notification 
## and http://www.mediawiki.org/wiki/Extension:Email_notification
## There are many more options for fine tuning available see
## /includes/DefaultSettings.php
## UPO means: this is also a user preference option
$wgEnotifUserTalk = true; # UPO
## added per req 2009-07-09 nooshanpet start
## Allow email notifications for changes
$wgEnotifWatchlist = true; # UPO
# Declare this twice so it works for all versions
$wgUsersNotifiedOnAllChanges =
$wgUsersNotifedOnAllChanges = array( 'Kristian' );
## added per req 2009-07-09 nooshanpet end
$wgEmailAuthentication = true;

$wgDBtype           = "mysql";
$wgDBserver         = "db.freecode.no";
$wgDBname           = "itgovernance";
$wgDBuser           = "itgovernance";
$wgDBpassword       = "wais1A_j";

# MySQL specific settings
$wgDBprefix         = "itgov_";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "TYPE=InnoDB";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

# Postgres specific settings
$wgDBport           = "5432";
$wgDBmwschema       = "mediawiki";
$wgDBts2schema      = "public";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

$wgVerifyMimeType= false;
#$wgMimeTypeFile= "/etc/mime.types";
#$wgMimeDetectorCommand= "file -bi"; #use external mime detector (Linux)
##$wgFileExtensions = array( 'png', 'gif', 'jpg', 'jpeg', 'pdf', 'odt', 'ott' ); 
$wgFileExtensions = array( 'png', 'gif', 'jpg', 'jpeg', 'pdf', 'odt', 'ott', 'zip', 'xls', 'doc' ); 

$wgEnableAPI = true;

$wgUseAjax = true;

$wgEnableMWSuggest = true;

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "en";

$wgProxyKey = "43aaefec6808239b21b64e9d87e47b659bd2fcfe3042ec1c2d46ba3e64fdadde";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'monobook';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = "Project:Copyrights";
#$wgRightsUrl = "https://www.gnu.org/licenses/gpl-3.0.html";
$wgRightsUrl = "http://www.gnu.org/licenses/gpl-3.0.html";
$wgRightsText = "GNU GPL v3";
$wgRightsIcon = "http://it-governance.freecode.no/w/images/5/59/Gplv3-88x31.png";
# $wgRightsCode = ""; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# debian specific include:
#if (is_file("/etc/mediawiki-extensions/extensions.php")) {
#        include( "/etc/mediawiki-extensions/extensions.php" );
#}

require_once("$IP/extensions/Cite/Cite.php");

require_once("$IP/extensions/ImageMap/ImageMap.php");

require_once("$IP/extensions/ParserFunctions/ParserFunctions.php");

require_once("$IP/extensions/CategoryTree/CategoryTree.php");

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$configdate = gmdate( 'YmdHis', @filemtime( __FILE__ ) );
$wgCacheEpoch = max( $wgCacheEpoch, $configdate );
	
